service: ms-gift-home-webapp

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  memorySize: 512
  timeout: 30
  region: us-east-2
  versionFunctions: false
  iam:
    role: arn:aws:iam::211125475552:role/RoleLambda-ms-gift-home-webapp

functions:
  get_items:
    handler: handler.get_items
    events:
      - httpApi:
          method: GET
          path: /get_items
          cors:
            origin: '*'
            headers:
              - Content-Type

  confirm_gift:
    handler: handler.confirm_gift
    events:
      - httpApi:
          method: POST
          path: /posts/confirm_gift
          cors:
            origin: '*'
            headers:
              - Content-Type